ALTER TABLE "Household" ADD COLUMN "savingsRecommendationMode" TEXT NOT NULL DEFAULT 'BALANCED';
ALTER TABLE "Household" ADD COLUMN "savingsTargetBps" INTEGER NOT NULL DEFAULT 5000;
ALTER TABLE "Household" ADD COLUMN "minimumDiscretionaryReserveMinor" INTEGER NOT NULL DEFAULT 100000;
ALTER TABLE "Household" ADD COLUMN "extraSafetyReserveMinor" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "Household" ADD COLUMN "minimumCashRetainedMinor" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "Household" ADD COLUMN "includeGoalContributionsInSafeToSave" BOOLEAN NOT NULL DEFAULT true;
ALTER TABLE "Household" ADD COLUMN "emergencyShortfallIncreasesRecommendation" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "Household" ADD COLUMN "conservativeConfidenceAdjustmentBps" INTEGER NOT NULL DEFAULT 2000;

CREATE TABLE "ExpectedIncomeSchedule" ("id" TEXT NOT NULL PRIMARY KEY,"householdId" TEXT NOT NULL,"name" TEXT NOT NULL,"amountMinor" INTEGER NOT NULL,"frequency" TEXT NOT NULL,"nextExpectedDate" DATETIME NOT NULL,"endDate" DATETIME,"twiceMonthlyDay1" INTEGER,"twiceMonthlyDay2" INTEGER,"accountId" TEXT,"recurringExpenseId" TEXT,"sourceType" TEXT NOT NULL DEFAULT 'USER_ENTERED',"confidence" TEXT NOT NULL DEFAULT 'HIGH',"active" BOOLEAN NOT NULL DEFAULT true,"notes" TEXT,"archivedAt" DATETIME,"isDemo" BOOLEAN NOT NULL DEFAULT false,"createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,"updatedAt" DATETIME NOT NULL,FOREIGN KEY("householdId") REFERENCES "Household"("id") ON DELETE CASCADE,FOREIGN KEY("accountId") REFERENCES "Account"("id") ON DELETE SET NULL,FOREIGN KEY("recurringExpenseId") REFERENCES "RecurringExpense"("id") ON DELETE SET NULL);
CREATE INDEX "ExpectedIncomeSchedule_householdId_active_archivedAt_idx" ON "ExpectedIncomeSchedule"("householdId","active","archivedAt"); CREATE INDEX "ExpectedIncomeSchedule_nextExpectedDate_idx" ON "ExpectedIncomeSchedule"("nextExpectedDate");
CREATE TABLE "ExpectedIncomeOccurrence" ("id" TEXT NOT NULL PRIMARY KEY,"householdId" TEXT NOT NULL,"scheduleId" TEXT NOT NULL,"expectedDate" DATETIME NOT NULL,"expectedAmountMinor" INTEGER NOT NULL,"status" TEXT NOT NULL DEFAULT 'UPCOMING',"satisfiedDate" DATETIME,"satisfiedTransactionId" TEXT,"amountDifferenceMinor" INTEGER NOT NULL DEFAULT 0,"notes" TEXT,"createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,"updatedAt" DATETIME NOT NULL,FOREIGN KEY("householdId") REFERENCES "Household"("id") ON DELETE CASCADE,FOREIGN KEY("scheduleId") REFERENCES "ExpectedIncomeSchedule"("id") ON DELETE CASCADE,FOREIGN KEY("satisfiedTransactionId") REFERENCES "Transaction"("id") ON DELETE SET NULL);
CREATE UNIQUE INDEX "ExpectedIncomeOccurrence_satisfiedTransactionId_key" ON "ExpectedIncomeOccurrence"("satisfiedTransactionId"); CREATE UNIQUE INDEX "ExpectedIncomeOccurrence_scheduleId_expectedDate_key" ON "ExpectedIncomeOccurrence"("scheduleId","expectedDate"); CREATE INDEX "ExpectedIncomeOccurrence_householdId_status_expectedDate_idx" ON "ExpectedIncomeOccurrence"("householdId","status","expectedDate");
CREATE TABLE "ScheduledObligation" ("id" TEXT NOT NULL PRIMARY KEY,"householdId" TEXT NOT NULL,"name" TEXT NOT NULL,"amountMinor" INTEGER NOT NULL,"dueDate" DATETIME NOT NULL,"frequency" TEXT NOT NULL,"accountId" TEXT,"categoryId" TEXT,"obligationType" TEXT NOT NULL,"sourceType" TEXT NOT NULL DEFAULT 'USER_ENTERED',"recurringExpenseId" TEXT,"debtAccountId" TEXT,"goalId" TEXT,"essentiality" TEXT NOT NULL DEFAULT 'ESSENTIAL',"confidence" TEXT NOT NULL DEFAULT 'HIGH',"active" BOOLEAN NOT NULL DEFAULT true,"notes" TEXT,"archivedAt" DATETIME,"isDemo" BOOLEAN NOT NULL DEFAULT false,"createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,"updatedAt" DATETIME NOT NULL,FOREIGN KEY("householdId") REFERENCES "Household"("id") ON DELETE CASCADE,FOREIGN KEY("accountId") REFERENCES "Account"("id") ON DELETE SET NULL,FOREIGN KEY("categoryId") REFERENCES "Category"("id") ON DELETE SET NULL,FOREIGN KEY("recurringExpenseId") REFERENCES "RecurringExpense"("id") ON DELETE SET NULL,FOREIGN KEY("debtAccountId") REFERENCES "Account"("id") ON DELETE SET NULL,FOREIGN KEY("goalId") REFERENCES "Goal"("id") ON DELETE SET NULL);
CREATE INDEX "ScheduledObligation_householdId_active_archivedAt_idx" ON "ScheduledObligation"("householdId","active","archivedAt"); CREATE INDEX "ScheduledObligation_dueDate_idx" ON "ScheduledObligation"("dueDate");
CREATE TABLE "ObligationOccurrence" ("id" TEXT NOT NULL PRIMARY KEY,"householdId" TEXT NOT NULL,"obligationId" TEXT NOT NULL,"expectedDate" DATETIME NOT NULL,"expectedAmountMinor" INTEGER NOT NULL,"status" TEXT NOT NULL DEFAULT 'UPCOMING',"satisfiedDate" DATETIME,"satisfiedTransactionId" TEXT,"amountDifferenceMinor" INTEGER NOT NULL DEFAULT 0,"notes" TEXT,"createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,"updatedAt" DATETIME NOT NULL,FOREIGN KEY("householdId") REFERENCES "Household"("id") ON DELETE CASCADE,FOREIGN KEY("obligationId") REFERENCES "ScheduledObligation"("id") ON DELETE CASCADE,FOREIGN KEY("satisfiedTransactionId") REFERENCES "Transaction"("id") ON DELETE SET NULL);
CREATE UNIQUE INDEX "ObligationOccurrence_satisfiedTransactionId_key" ON "ObligationOccurrence"("satisfiedTransactionId"); CREATE UNIQUE INDEX "ObligationOccurrence_obligationId_expectedDate_key" ON "ObligationOccurrence"("obligationId","expectedDate"); CREATE INDEX "ObligationOccurrence_householdId_status_expectedDate_idx" ON "ObligationOccurrence"("householdId","status","expectedDate");
